#  compose.yaml
services:
  postgres:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cambridge_net

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    environment:
      TZ: ${TZ}
    networks:
      - cambridge_net
    ports:
      - '${REDIS_PORT}:6379'

  auth-service:
    build:
      context: .
    container_name: ${AUTH_SERVICE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - redis
      - postgres
    networks:
      - cambridge_net
      - app-network

volumes:
  pgdata:

networks:
  cambridge_net:
    driver: bridge
  app-network:
    external: true
    name: app-network
